[package]
name = "v_utils"
version = "0.1.41"
edition = "2021"
resolver = "1"
description = "My utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Valera6/utils"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
serde = { version = "1.0.195", features = ["derive"] }
dirs = { version = "5.0.1", optional = true }
#polars = { version = "0.36.2", optional = true }
chrono = { version = "0.4.31", optional = true }
serde_json = "1.0.111"

# amazing cheatsheet: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
[features]
default = ["full"]

files = ["dirs"] 
klines = ["chrono"]
#fuck_me = ["klines", "polars"]

#full = ["files", "fuck_me"]
full = ["files", "klines"]
