[package]
name = "v_utils"
version = "1.9.0"
edition = "2021"
description = "My utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/valeratrades/v_utils"

[dev-dependencies]
claim = "^0.5.0"
insta = "^1.40.0"
trybuild = { version = "^1.0.99", features = ["diff"] }
v_utils_macros = { path = "../v_utils_macros" }

[dependencies]
# unconditional
eyre = "^0.6.12" # not color-eyre, that one is for client-side
derive-new = "^0.7.0"
serde = { version = "^1.0.210", features = ["derive"] }
serde_json = "^1.0.128"
tokio = { version = "^1.40.0", features = ["full", "io-util"] }
function_name = "^0.3.0" # weird to include this without a feature flag, but this is a utils crate in the end

# # optional
async-sse = { version = "^5.1.0", optional = true }
bytes = { version = "^1.7.2", optional = true }
reqwest = { version = "^0.12.8", features = ["json", "blocking", "stream"], optional = true }
chrono = { version = "^0.4.38", optional = true }
dirs = { version = "^5.0.1", optional = true }
futures = { version = "^0.3.31", optional = true }
quote = { version = "^1.0.37", optional = true }
rand = { version = "^0.8.5", optional = true }
rand_distr = { version = "^0.4.3", optional = true }

tracing = { version = "^0.1.40", features = ["log", "std", "async-await"], optional = true }
tracing-bunyan-formatter = { version = "^0.3.9", optional = true }
tracing-subscriber = { version = "^0.3.18", features = ["fmt", "json", "registry", "env-filter"], optional = true }
tracing-log = { version = "^0.2.0", optional = true }
tracing-error = { version = "^0.2.0", optional = true }
console-subscriber = { version = "0.4.0", optional = true }
#

v_utils_macros = { path = "../v_utils_macros", version = "^1.5.0", optional = true }
#

# amazing cheatsheet: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
[features]
default = []

io = ["dirs"] 
trades = ["chrono"]
macros = ["v_utils_macros"]
llm = ["reqwest", "futures", "bytes"]
tracing = ["dep:tracing", "dep:tracing-bunyan-formatter", "dep:tracing-subscriber", "dep:tracing-log", "dep:tracing-error", "dep:console-subscriber"]
distributions = ["rand", "rand_distr"]

full = ["io", "macros", "trades", "llm", "tracing", "distributions"]
