[package]
name = "v_utils"
version = "0.1.51"
edition = "2021"
description = "My utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Valera6/v_utils"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.79"
serde = { version = "^1.0.195", features = ["derive"] }
dirs = { version = "^5.0.1", optional = true }
chrono = { version = "^0.4.31", optional = true }
serde_json = "^1.0.111"
proc-macro2 = { version = "*", optional = true }
syn = { version = "2.0.48", features = ["full"], optional = true }
quote = { version = "1.0.35", optional = true }
v_utils_macros = { path = "../v_utils_macros", version = "*", optional = true }

# amazing cheatsheet: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
[features]
default = ["full"]

io = ["dirs"] 
trades = ["chrono"]
macros = ["v_utils_macros"]

full = ["io", "macros", "trades"]
