[package]
name = "v_utils"
version = "1.0.7"
edition = "2021"
description = "My utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Valera6/v_utils"


[[test]]
name = "tests"
path = "tests/unit_tests_main.rs"

[dev-dependencies]
trybuild = { version = "^1.0.89", features = ["diff"]}
v_utils_macros = { path = "../v_utils_macros" }

[dependencies]
anyhow = "^1.0.79"
serde = { version = "^1.0.195", features = ["derive"] }
serde_json = "^1.0.111"
dirs = { version = "^5.0.1", optional = true }
chrono = { version = "^0.4.31", optional = true }
proc-macro2 = { version = "^1.0.78", optional = true }
syn = { version = "2.0.48", features = ["full"], optional = true }
quote = { version = "1.0.35", optional = true }
reqwest = { version = "0.11.26", features = ["json", "blocking"], optional = true }

v_utils_macros = { path = "../v_utils_macros", version = "^1.0.1", optional = true }

# amazing cheatsheet: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
[features]
default = ["full"]

io = ["dirs"] 
trades = ["chrono"]
macros = ["v_utils_macros"]
llm = ["reqwest"]

full = ["io", "macros", "trades", "llm"]
