[package]
name = "v_utils"
version = "2.0.2"
edition = "2021"
description = "My utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/valeratrades/v_utils"

[dev-dependencies]
claim = "^0.5.0"
insta = "^1.42.0"
trybuild = { version = "^1.0.101", features = ["diff"] }
v_utils_macros = { path = "../v_utils_macros" }

[dependencies]
# unconditional
eyre.workspace = true
const_format = "0.2.34"
serde.workspace = true
tracing = { version = "^0.1.41", features = ["log", "std", "async-await"] }
derive-new = "^0.7.0"
serde_json = "^1.0.135"
tokio = { version = "^1.43.0", features = ["full", "io-util"] }
function_name = "^0.3.0" # weird to include this without a feature flag, but this is a utils crate in the end
num = "^0.4.3" # same thing as `function_name` - this is used by `utlils` mod
thiserror = "2.0.10"

# # optional
async-sse = { version = "^5.1.0", optional = true }
bytes = { version = "^1.9.0", optional = true }
reqwest = { version = "^0.12.12", default-features = false, features = ["json", "blocking", "stream", "rustls-tls"], optional = true }
chrono = { version = "^0.4.39", optional = true }
dirs = { version = "^5.0.1", optional = true }
futures = { version = "^0.3.31", optional = true }
quote = { version = "^1.0.38", optional = true }
rand = { version = "^0.8.5", optional = true }
rand_distr = { version = "^0.4.3", optional = true }

tracing-bunyan-formatter = { version = "^0.3.10", optional = true }
tracing-subscriber = { version = "^0.3.19", features = ["fmt", "json", "registry", "env-filter"], optional = true }
tracing-log = { version = "^0.2.0", optional = true }
tracing-error = { version = "^0.2.1", optional = true }
console-subscriber = { version = "0.4.1", optional = true }
#

v_utils_macros = { path = "../v_utils_macros", version = "^2.0.2", optional = true }
xdg = "2.5.2"
macro-attr = { version = "0.2.0", features = ["unstable-macros-1-1"] }
derive_more = { version = "1.0.0", features = ["full"] }
#

# amazing cheatsheet: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
[features]
default = []

io = ["dirs"] 
trades = ["chrono"]
macros = ["v_utils_macros"]
llm = ["reqwest", "futures", "bytes"]
tracing = ["dep:tracing-bunyan-formatter", "dep:tracing-subscriber", "dep:tracing-log", "dep:tracing-error", "dep:console-subscriber"]
distributions = ["rand", "rand_distr"]

full = ["io", "macros", "trades", "llm", "tracing", "distributions"]

# dev only
slow_tests = []
