[package]
name = "v_utils"
version = "1.4.1"
edition = "2021"
description = "My utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/valeratrades/v_utils"

[dev-dependencies]
trybuild = { version = "^1.0.96", features = ["diff"]}
v_utils_macros = { path = "../v_utils_macros" }
claim = "^0.5.0"

[dependencies]
anyhow = "^1.0.86"
derive-new = "^0.6.0"
serde = { version = "^1.0.203", features = ["derive"] }
serde_json = "^1.0.117"
dirs = { version = "^5.0.1", optional = true }
chrono = { version = "^0.4.38", optional = true }
quote = { version = "^1.0.36", optional = true }
reqwest = { version = "^0.12.5", features = ["json", "blocking", "stream"], optional = true }
futures = { version = "^0.3.30", optional = true }
tokio = { version = "^1.38.0", features = ["full", "io-util"], optional = true }
async-sse = { version = "^5.1.0", optional = true }
bytes = { version = "^1.6.0", optional = true }

tracing = { version = "^0.1.40", features = ["log", "std", "async-await"], optional = true }
tracing-bunyan-formatter = { version = "^0.3.9", optional = true }
tracing-subscriber = { version = "^0.3.18", features = ["fmt", "json", "registry", "env-filter"], optional = true }
#tracing-log = { version = "^0.2.0", optional = true }


v_utils_macros = { path = "../v_utils_macros", version = "^1.2.7", optional = true }
insta = "1.39.0"

# amazing cheatsheet: https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
[features]
default = ["full"]

io = ["dirs"] 
trades = ["chrono"]
macros = ["v_utils_macros"]
llm = ["reqwest", "futures", "tokio", "bytes"]
utils = ["tracing", "tracing-bunyan-formatter", "tracing-subscriber"]

full = ["io", "macros", "trades", "llm", "utils"]
tokio = ["dep:tokio"]
