[package]
name = "v_utils_macros"
version = "1.2.4"
edition = "2021"
description = "Macros for my utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Valera6/v_utils"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
toml = "0.8.14"
trybuild = { version = "^1.0.96", features = ["diff"]}
v_utils = { path = "../v_utils" }

[dependencies]
proc-macro2 = { version = "^1.0.86" }
syn = { version = "^2.0.67", features = ["full", "extra-traits"] }
quote = { version = "^1.0.36" }
anyhow = "^1.0.86"
serde = { version = "1.0.203", features = ["derive"] }
