[package]
name = "v_utils_macros"
version = "0.3.2"
edition = "2021"
description = "Macros for my utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Valera6/v_utils"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dev-dependencies]
trybuild = { version = "^1.0.89", features = ["diff"]}

[dependencies]
proc-macro2 = { version = "^1.0.78" }
syn = { version = "^2.0.48", features = ["full", "extra-traits"] }
quote = { version = "^1.0.35" }

anyhow = { version = "^1.0.79" }
