[package]
name = "v_utils_macros"
version = "0.1.0"
edition = "2021"
description = "Macros for my utils crate"
rust-version = "1.75"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Valera6/v_utils"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { version = "^1.0.78" }
syn = { version = "^2.0.48", features = ["full"] }
quote = { version = "^1.0.35" }

anyhow = { version = "^1.0.79" }

[lib]
proc-macro = true
