on:
  push:
    paths:
      - "v_utils/src/llm/**"
  pull_request:
    paths:
      - "v_utils/src/llm/**"

jobs:
  test:
    name: Expensive tests with llm queries
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Set RUSTFLAGS for release branch
        run: echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/release'
      - name: Enable type layout randomization
        run: echo RUSTFLAGS=${RUSTFLAGS}\ -Zrandomize-layout\ --cfg=exhaustive >> $GITHUB_EN
      - run: cargo update
      - run: cargo check
      - run: RUSTFLAGS="${RUSTLAGS}\ --cfg llm_test" cargo test

